<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>NineP.Benchmarks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/NineP.Client/NineP.Client.csproj" />
    <ProjectReference Include="../../src/NineP.Server/NineP.Server.csproj" />
    <ProjectReference Include="../NineP.TestSupport/NineP.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
